version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    # Files stored in the default project in the root of this repo
    directory: "/"
    schedule:
      interval: "weekly"
