name: React-Native CI

on:
  push:
    branches: [ main, next ]
    paths: [ '.github/**', 'fakewalletreact/**', 'js/**' ]
  pull_request:
    branches: [ main, next ]
    paths: [ '.github/**', 'fakewalletreact/**', 'js/**' ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'fakewalletreact/package.json' # note - node engine should match between fakewalletreact/ and js/

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: |
            js/pnpm-lock.yaml
            fakewalletreact/pnpm-lock.yaml
          package_json_file: 'js/package.json'

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v6

      - name: '[js] Install pnpm dependencies'
        working-directory: 'js/'
        run: pnpm install --frozen-lockfile
      - name: '[js] Lint'
        working-directory: 'js/'
        run: pnpm lint
        continue-on-error: true # TODO: fix all lint issues and remove this line
      - name: '[js] Build'
        working-directory: 'js/'
        run: pnpm build

      - name: '[fakewalletreact] Install pnpm dependencies'
        working-directory: 'fakewalletreact/'
        run: pnpm install --frozen-lockfile
      - name: '[fakewalletreact] Lint'
        working-directory: 'fakewalletreact/'
        run: pnpm lint
        continue-on-error: true # TODO: fix all lint issues and remove this line
      - name: '[fakewalletreact] Build'
        working-directory: 'fakewalletreact/'
        run: pnpm android:build
